# RandomForest Summary

# Step1 Data Import

The data we used is data.xlsx which includes 30969 samples and 65 features.
Here is a summary of these features about the NULL values.

In [2]:
Nullsummary

,variable type,Number of null,Items
Patient_DB_ID,ID,0,"[1260432, 1260597, 1260621, 1260672, 1259543, ..."
Procedure_Unique_Identifier,ID,0,"[243848, 243867, 243871, 243881, 242629, 24263..."
Procedure Year,Numeric_int,0,"[2012, 2011, 2010, 2013, 2015, 2014]"
Procedure Quarter of year,categorical,0,"['Q4', 'Q1', 'Q3', 'Q2']"
Procedure Month,categorical,0,"['November', 'October', 'January', 'February',..."
Procedure MonthNumber,Numeric_int,0,"[11, 10, 1, 2, 8, 9, 3, 5, 6, 4, 12, 7]"
Procedure Week of year,Categorical,0,"[' Week 46', ' Week 45', ' Week 47', ' Week 43..."
Procedure Day of Month,Numeric_int,0,"[12, 8, 21, 7, 27, 28, 6, 31, 4, 10, 29, 30, 1..."
Day of Week,Categorical,0,"['Monday', 'Thursday', 'Wednesday', 'Saturday'..."
Time Waiting for Procedure,Categorical,9281,"['Within 1 week', 'Within 2 weeks', 'Within 3 ..."
Procedure Group,Categorical,0,"['[Catheter]', '[Electrophysiology]']"
Procedure TypeI,Categorical,0,"['[Catheter Lab Diagnostic]', '[Pacing &amp; I..."
Booked Procedure,Categorical,1,"['[PCI standard]', '[Left Heart Catheter PCI]..."
PREVIOUS_MI,Categorical,8601,"['No', 'Unknown', 'Yes', nan]"
PREVIOUS_CABG,Categorical,8601,"['No', 'Unknown', 'Yes', nan]"
PREVIOUS_PCI,Categorical,8601,"['No', 'Unknown', 'Yes', nan]"
RENAL_DISEASE,Categorical,8601,"['Creatinine 140 - 200 umol/L', 'Creatinine &g..."
HISTORY_HYPERTENSION,Categorical,30969,[nan]
FAMILY_HIST_CAD,Categorical,8601,"['No', 'Unknown', 'Yes', nan]"
EJECTION_FRACTION,Numeric_int,26288,"[nan, 35.0, 55.0, 40.0, 60.0, 50.0, 38.0, 1.0,..."
EJECTION_FRACTION_CAT,Categorical,11550,"['Good (LVEF &gt; 50%)', 'Unknown', 'Moderate ..."
TOTAL_CHOLESTEROL,Numeric_float,24364,"[nan, 4.3, 3.9, 3.4, 4.5, 5, 6, 3.1, 4.4, 7.1,..."
HEIGHT,Numeric_float,20379,"[nan, 1.5, 1.76, 1.8999999999999999, 1.73, 1.7..."
WEIGHT,Numeric_float,19497,"[nan, 102.0, 75.0, 95.0, 97.5, 70.0, 77.0, 68...."
BMI,Numeric_float,20402,"[nan, 45.329999999999998, 24.210000000000001, ..."
DIABETES_TYPE,Categorical,9141,"['Not Diabetic', 'Unknown - data missing', nan..."
DIABETES_CONTROL,Categorical,30717,"[nan, 'Insulin']"
Smoker,Categorical,10590,"['No', 'Yes', 'Ex Smoker', 'Unknown', nan, 'Oc..."
HEART_RATE,Numeric_int,24477,"[nan, 60.0, 56.0, 63.0, 62.0, 68.0, 114.0, 74...."
Euroscore,Numeric_int,30842,"[nan, 6.0, 3.0, 4.0, 0.0, 5.0, 1.0, 2.0, 7.0, ..."
CLINICAL_SYNDROME,Categorical,16095,"['Acute Coronary Syndrome (ACS/AMI)', 'Stable'..."
Indication for intervention,Categorical,16189,"['ACS - UA, NSTEMI or convalescent STEMI', 'St..."
ACS,Categorical,14360,"['YES', 'Unknown', nan, 'NO']"
Presenting ECG,Categorical,22456,"['Normal Sinus Rhythm', 'T wave changes', nan,..."
Thrombolysis,Categorical,22458,"['No', nan, 'Yes &lt; 1 day', 'Unknown', 'Yes ..."
COMPLICATION,Categorical,29518,"[nan, 'Asystolic Episode during procedure', '0..."
ACCESS_TYPE,Categorical,4339,"['Arterial', 'Arterial;Arterial', nan, 'Arteri..."
ACCESS_SITE,Categorical,4339,"['RRA', 'RFA', 'RRA;RFA', nan, 'RFA;RFV', 'RFA..."
ACCESS_METHOD,Categorical,4339,"['Percutaneous', 'Percutaneous;Percutaneous', ..."
CATH EVENTS,Categorical,14345,"['Balloon - Compliant, Abbott vascular, TREK B..."
Radiation Dose,Numeric_int,2423,"[5147.0, 5798.0, 9762.0, 58500.0, 4845.0, 3064..."
Replacement Device?,Categorical,28541,"[nan, 'N', 'F', 'T']"
Replacement Reason,Categorical,30713,"[nan, 'Normal EOL', 'Expected battery depletio..."
Procedure typeII,Categorical,28549,"[nan, 'ICD', 'Permanent pacemaker', 'Loop reco..."
Device type,Categorical,28549,"[nan, 'Dual chamber', 'Single chamber', 'Bi-ve..."
Device type.1,Categorical,28549,"[nan, 'Sub-rectus', 'Unknown', 'Supra-rectus']"
ARRHYTHMIA?,Categorical,0,"['[Arrhythmia Type]:[None]', '[Arrhythmia Type..."
No. of Ablations?,Numeric_int,0,"[0, 1, 2, 3]"
No. Vessels Attempted,Numeric_int,16095,"[1.0, nan, 2.0, 6.0, 3.0, 0.0, 4.0, 5.0]"
No. Chronic Occlusions Attempted,Numeric_int,16730,"[0.0, nan, 1.0, 2.0, 4.0, 3.0]"
No. Lesions Attempted,Numeric_int,16673,"[1.0, nan, 2.0, 0.0, 3.0, 4.0, 5.0, 6.0]"
No. Lesions Successful,Numeric_int,16748,"[1.0, nan, 0.0, 2.0, 3.0, 4.0, 275.0, 5.0, 235..."
Largest balloon/Stent Used,Numeric_float,16987,"[2.5, 3.5, 3.0, 4.0, nan, 2.0, 2.75, 2.25, 3.2..."
No. of Restenosis attempted,Numeric_int,16856,"[23.0, 0.0, nan, 1.0, 2.0, 3.0, 24.0, 9.0]"
No. Instent restenosis attempted,Numeric_int,16864,"[0.0, nan, 1.0, 2.0, 3.0, 9.0]"
No. Stents Used,Numeric_int,16806,"[1.0, 2.0, nan, 0.0, 4.0, 3.0, 5.0, 6.0, 7.0, ..."
No. Drug Eluting Stents Used,Numeric_int,16833,"[1.0, 2.0, 0.0, nan, 4.0, 3.0, 15.0, 5.0, 6.0,..."
Longest Stent/Treated segment,Numeric_int,17058,"[23.0, 16.0, 44.0, 18.0, 41.0, 28.0, nan, 24.0..."
Indication for stent,Categorical,30964,"[nan, 'Stent used - Elective']"
LMS Protected,Categorical,30964,"[nan, 'Yes']"
OUTCOME,Categorical,10395,"['Alive', 'Dead', nan, 'Unknown']"
LENGTH_STAY_PROC_TO_DISCH,Numeric_int,30487,"[nan, 9.0, 68.0, 4.0, 0.0, 67.0, 6.0, 100.0, 7..."
GENDER,Categorical,0,"['Male', 'Female', 'Unknown']"
Age,Numeric_int,0,"[52, 53, 51, 83, 77, 67, 48, 69, 86, 60, 79, 5..."
Ethnicity,Categorical,886,"['White British', 'White', nan, 'Not stated', ..."

# Step2 Transform data

Depending on the number of Null, we delete the features which include so many null values (number >= 20000).

For categorical feature, we treated the null value as a new categorical 0. For numerical feature, we 
replace the null value with the mean of the total values.

The data after transform looks as following:

In [20]:
data

,Procedure Year,Procedure Quarter of year,Procedure Month,Procedure MonthNumber,Procedure Week of year,Procedure Day of Month,Day of Week,Time Waiting for Procedure,Procedure Group,Procedure TypeI,Booked Procedure,PREVIOUS_MI,PREVIOUS_CABG,PREVIOUS_PCI,RENAL_DISEASE,FAMILY_HIST_CAD,EJECTION_FRACTION_CAT,BMI,DIABETES_TYPE,DIABETES_CONTROL,Smoker,ACS,ACCESS_TYPE,ACCESS_SITE,ACCESS_METHOD,Radiation Dose,Procedure typeII,ARRHYTHMIA?,No. of Ablations?,No. Vessels Attempted,No. Chronic Occlusions Attempted,No. Lesions Attempted,No. Lesions Successful,Largest balloon/Stent Used,No. of Restenosis attempted,No. Instent restenosis attempted,No. Stents Used,No. Drug Eluting Stents Used,Longest Stent/Treated segment,OUTCOME,GENDER,Age,Ethnicity
0,2012.0,3,9,11.0,40,12.0,1,7,0,1,165,1,1,1,2,1,1,4902.49929,3,0,3,3,1,69,3,5147.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,2.500000,23.000000,0.000000,1.000000,1.000000,23.000000,1,1,52.0,17
1,2012.0,3,9,11.0,39,8.0,4,7,0,1,129,1,1,1,2,1,1,4902.49929,3,0,7,3,1,69,3,5798.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,1.000000,1.000000,16.000000,1,1,53.0,17
2,2012.0,3,9,11.0,41,21.0,6,8,0,1,165,1,1,1,2,1,1,45.33000,3,0,1,2,1,69,3,9762.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,2.000000,2.000000,44.000000,1,0,51.0,17
3,2012.0,3,9,11.0,39,7.0,6,9,0,1,129,2,2,2,1,2,6,4902.49929,10,0,6,3,1,69,3,58500.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,1.000000,1.000000,18.000000,2,1,83.0,17
4,2012.0,3,10,10.0,37,27.0,2,9,0,1,129,1,1,1,2,1,6,4902.49929,3,0,3,3,1,35,3,4845.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,2.000000,0.000000,41.000000,1,1,77.0,17
5,2012.0,3,10,10.0,37,27.0,2,7,0,1,129,3,3,3,3,3,3,24.21000,3,0,3,3,1,35,3,3064.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,1.000000,0.000000,28.000000,1,1,67.0,17
6,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,5,4902.49929,3,0,7,3,1,69,3,4153.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,18.000000,1,1,48.0,17
7,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,2,2,2,1,2,1,28.25000,3,0,6,0,1,69,3,8978.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,1,1,69.0,17
8,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,3,4902.49929,3,0,1,3,2,79,5,6312.0,0,32,0.0,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,22.275609,1,0,86.0,17
9,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,6,4902.49929,3,0,7,3,2,79,5,6521.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,24.000000,1,1,60.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30959,2015.0,3,2,12.0,48,31.0,4,7,0,1,151,3,3,3,3,3,1,4902.49929,0,0,0,0,1,35,3,1649.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,1,1,87.0,17
30960,2015.0,3,2,12.0,48,31.0,4,7,0,1,151,1,1,1,2,1,3,4902.49929,6,0,6,0,1,35,3,3399.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,1,1,46.0,17
30961,2015.0,3,2,12.0,48,30.0,6,0,0,1,129,1,1,1,2,1,6,23.53000,3,0,0,3,1,35,3,2394.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,1.000000,1.000000,16.000000,0,0,75.0,13
30962,2015.0,3,2,12.0,48,31.0,4,7,0,1,151,1,1,1,2,1,1,25.95000,7,0,3,0,1,69,3,2411.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,1,1,47.0,13
30963,2015.0,3,2,12.0,46,13.0,3,0,0,1,129,1,1,1,2,1,1,4902.49929,3,0,3,0,1,69,3,2556.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,0,1,79.0,17
30964,2015.0,3,2,12.0,46,13.0,3,0,0,1,37,1,1,1,2,1,1,30.93000,3,0,3,3,1,69,3,11316.0,0,32,0.0,2.000000,0.000000,3.000000,3.000000,24.000000,0.000000,0.000000,3.000000,3.000000,3.000000,0,1,45.0,17
30965,2015.0,3,2,12.0,46,13.0,3,0,0,1,129,3,3,3,3,3,6,26.23000,6,0,3,3,1,69,3,3734.0,0,32,0.0,1.000000,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,0,1,78.0,13
30966,2015.0,3,2,12.0,46,13.0,3,7,0,1,129,1,1,1,2,1,3,19.53000,3,0,6,2,1,69,3,3920.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,2.500000,0.000000,0.000000,1.000000,1.000000,20.000000,2,0,97.0,13
30967,2015.0,3,2,12.0,46,14.0,1,7,0,1,165,1,1,1,2,1,1,4902.49929,3,0,0,2,1,69,3,9726.0,0,32,0.0,2.000000,0.000000,3.000000,3.000000,3.000000,0.000000,0.000000,3.000000,3.000000,16.000000,1,1,47.0,17
30968,2015.0,3,2,12.0,46,14.0,1,0,1,2,54,0,0,0,0,0,0,4902.49929,0,0,0,0,0,0,0,451.0,3,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,0,0,81.0,17

# Step3 Balance Outcome

Since the OUTCOME is unbalanced, which has 253 of Dead and 20295 of Alive. We need oversampling and 
undersampling to control each outcome with 1265 rows.

Oversampling: copy the data for five times.
Undersampling: choose the first 1265 rows of Alive

results as following:

In [21]:
data_new

,Procedure Year,Procedure Quarter of year,Procedure Month,Procedure MonthNumber,Procedure Week of year,Procedure Day of Month,Day of Week,Time Waiting for Procedure,Procedure Group,Procedure TypeI,Booked Procedure,PREVIOUS_MI,PREVIOUS_CABG,PREVIOUS_PCI,RENAL_DISEASE,FAMILY_HIST_CAD,EJECTION_FRACTION_CAT,BMI,DIABETES_TYPE,DIABETES_CONTROL,Smoker,ACS,ACCESS_TYPE,ACCESS_SITE,ACCESS_METHOD,Radiation Dose,Procedure typeII,ARRHYTHMIA?,No. of Ablations?,No. Vessels Attempted,No. Chronic Occlusions Attempted,No. Lesions Attempted,No. Lesions Successful,Largest balloon/Stent Used,No. of Restenosis attempted,No. Instent restenosis attempted,No. Stents Used,No. Drug Eluting Stents Used,Longest Stent/Treated segment,OUTCOME,GENDER,Age,Ethnicity
0,2012.0,3,9,11.0,40,12.0,1,7,0,1,165,1,1,1,2,1,1,4902.49929,3,0,3,3,1,69,3,5147.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,2.500000,23.000000,0.000000,1.000000,1.000000,23.000000,1,1,52.0,17
1,2012.0,3,9,11.0,39,8.0,4,7,0,1,129,1,1,1,2,1,1,4902.49929,3,0,7,3,1,69,3,5798.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,1.000000,1.000000,16.000000,1,1,53.0,17
2,2012.0,3,9,11.0,41,21.0,6,8,0,1,165,1,1,1,2,1,1,45.33000,3,0,1,2,1,69,3,9762.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,2.000000,2.000000,44.000000,1,0,51.0,17
4,2012.0,3,10,10.0,37,27.0,2,9,0,1,129,1,1,1,2,1,6,4902.49929,3,0,3,3,1,35,3,4845.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,2.000000,0.000000,41.000000,1,1,77.0,17
5,2012.0,3,10,10.0,37,27.0,2,7,0,1,129,3,3,3,3,3,3,24.21000,3,0,3,3,1,35,3,3064.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,1.000000,0.000000,28.000000,1,1,67.0,17
6,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,5,4902.49929,3,0,7,3,1,69,3,4153.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,18.000000,1,1,48.0,17
7,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,2,2,2,1,2,1,28.25000,3,0,6,0,1,69,3,8978.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,1,1,69.0,17
8,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,3,4902.49929,3,0,1,3,2,79,5,6312.0,0,32,0.0,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,22.275609,1,0,86.0,17
9,2012.0,3,10,10.0,38,28.0,3,7,0,1,129,1,1,1,2,1,6,4902.49929,3,0,7,3,2,79,5,6521.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,24.000000,1,1,60.0,17
11,2012.0,3,9,11.0,39,7.0,6,8,0,1,165,1,1,1,2,1,1,31.74000,3,0,1,2,1,69,3,1143.0,0,32,0.0,1.000000,0.000000,2.000000,2.000000,2.750000,0.000000,0.000000,2.000000,2.000000,30.000000,1,1,57.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29282,2015.0,1,6,6.0,18,25.0,4,7,0,1,129,1,1,1,2,1,6,4902.49929,3,0,0,3,1,35,3,8839.0,0,32,0.0,1.000000,0.000000,3.000000,3.000000,4.500000,0.000000,0.000000,3.000000,0.000000,24.000000,2,1,51.0,13
29567,2015.0,2,5,7.0,24,29.0,6,7,0,1,129,1,1,1,2,1,6,4902.49929,3,0,3,3,1,35,3,3816.0,0,32,0.0,3.000000,0.000000,2.000000,2.000000,4.500000,0.000000,0.000000,2.000000,2.000000,56.000000,2,1,82.0,17
29644,2015.0,2,1,8.0,27,17.0,1,7,0,1,129,1,1,1,2,1,1,4902.49929,3,0,1,0,1,35,3,1683.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,2,1,40.0,17
29822,2015.0,2,5,7.0,24,27.0,1,7,0,1,129,1,1,1,2,1,5,18.94000,3,0,3,3,1,69,3,8059.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,2.500000,0.000000,0.000000,1.000000,1.000000,18.000000,2,1,85.0,17
29871,2015.0,2,5,7.0,24,29.0,6,7,0,1,129,3,3,3,3,3,6,4902.49929,3,0,6,0,1,35,3,3163.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,2,1,68.0,17
30071,2015.0,2,1,8.0,26,11.0,5,7,0,1,129,2,2,2,1,2,3,4902.49929,3,0,6,3,1,35,3,7515.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.500000,0.000000,0.000000,1.000000,1.000000,24.000000,2,1,84.0,13
30298,2015.0,2,1,8.0,28,28.0,0,7,0,1,165,3,3,3,3,3,3,27.92000,3,0,1,3,1,35,3,13094.0,0,32,0.0,3.000000,0.000000,2.000000,1.000000,3.000000,0.000000,0.000000,2.000000,2.000000,30.000000,2,1,88.0,17
30560,2015.0,2,11,9.0,30,11.0,0,7,0,1,129,1,1,1,2,1,0,26.23000,3,0,6,0,2,36,5,4564.0,0,32,0.0,1.232419,0.077323,1.281337,1.362211,3.226638,0.030398,0.042255,1.375697,1.212153,22.275609,2,1,70.0,17
30941,2015.0,3,9,11.0,42,27.0,0,8,0,1,129,3,3,3,3,3,5,35.16000,3,0,6,3,8,85,5,2431.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,24.000000,2,0,43.0,17
30966,2015.0,3,2,12.0,46,13.0,3,7,0,1,129,1,1,1,2,1,3,19.53000,3,0,6,2,1,69,3,3920.0,0,32,0.0,1.000000,0.000000,1.000000,1.000000,2.500000,0.000000,0.000000,1.000000,1.000000,20.000000,2,0,97.0,13

# Step 4 Feature Importances of Random Forest Tree

The feature importances ranking as following:

Feature Importances:
1. Procedure Year (0.423118)
2. Procedure Quarter of year (0.083667)
3. Procedure Month (0.041721)
4. Procedure MonthNumber (0.041068)
5. Procedure Week of year (0.040501)
6. Procedure Day of Month (0.038533)
7. Day of Week (0.038416)
8. Time Waiting for Procedure (0.036290)
9. Procedure Group (0.022360)
10. Procedure TypeI (0.021566)
11. Booked Procedure (0.019270)
12. PREVIOUS_MI (0.015021)
13. PREVIOUS_CABG (0.013287)
14. PREVIOUS_PCI (0.011133)
15. RENAL_DISEASE (0.010737)
16. FAMILY_HIST_CAD (0.010492)
17. EJECTION_FRACTION_CAT (0.010352)
18. BMI (0.010306)
19. DIABETES_TYPE (0.010148)
20. DIABETES_CONTROL (0.009854)
21. Smoker (0.008302)
22. ACS (0.008187)
23. ACCESS_TYPE (0.008053)
24. ACCESS_SITE (0.008032)
25. ACCESS_METHOD (0.007349)
26. Radiation Dose (0.005894)
27.  Procedure typeII (0.005612)
28. ARRHYTHMIA? (0.005486)
29. No. of Ablations? (0.005348)
30. No. Vessels Attempted (0.004600)
31. No. Chronic Occlusions Attempted (0.003709)
32. No. Lesions Attempted (0.003273)
33. No. Lesions Successful (0.003214)
34. Largest balloon/Stent Used (0.003104)
35. No. of Restenosis attempted (0.002917)
36. No. Instent restenosis attempted (0.002821)
37. No. Stents Used (0.002200)
38. No. Drug Eluting Stents Used (0.001693)
39. Longest Stent/Treated segment (0.001296)
40. OUTCOME (0.000543)
41. GENDER (0.000389)
42. Age (0.000137)

# Step5 Random Forest Classifier predict

Let select the features based on their importance. Predicted by Cross-Validation

In [18]:
nrtc_cv( 'OUTCOME' , var , data )

C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

(0.93823339585427334, array([ 1.,  1.,  1., ...,  1.,  1.,  0.]))

# CODE

In [1]:
# Import the data and output the null summary
from pandas import DataFrame
import pandas
from sklearn.ensemble import RandomForestClassifier
path = 'C:\\Users\\310249682\Documents\\data.xlsx'
data = pandas.read_excel(path)
pandas.set_option('display.max_columns',80)
pandas.set_option('display.max_rows',66)
NaN_count = [len(data[i])-data[i].count() for i in data.columns]
variable = [str([j.encode("utf-8") if type(j) is unicode else j for j in list(data[i].unique())]) for i in data.columns]
vtype = ['ID','ID','Numeric_int','categorical','categorical','Numeric_int','Categorical','Numeric_int','Categorical','Categorical',
         'Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Numeric_int',
         'Categorical','Numeric_float','Numeric_float','Numeric_float','Numeric_float','Categorical','Categorical','Categorical','Numeric_int','Numeric_int',
         'Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical',
         'Numeric_int','Categorical','Categorical','Categorical','Categorical','Categorical','Categorical','Numeric_int','Numeric_int','Numeric_int',
         'Numeric_int','Numeric_int','Numeric_float','Numeric_int','Numeric_int','Numeric_int','Numeric_int','Numeric_int','Categorical','Categorical',
         'Categorical','Numeric_int','Categorical','Numeric_int','Categorical']
dtype = pandas.DataFrame(data = data.dtypes, columns = ['Type'])
dvtype = pandas.DataFrame(data = vtype, columns = ['variable type'],index = dtype.index)
dNaN = pandas.DataFrame(data = NaN_count, columns = ['Number of null'],index = dtype.index)
dvar = pandas.DataFrame(data = variable, columns = ['Items'],index = dtype.index)
frame=[dvtype,dNaN,dvar]
Nullsummary = pandas.concat(frame,axis=1)

In [4]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn import ensemble as ske
from sklearn.preprocessing import Imputer
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import cross_val_predict
import patsy
from numpy import float32
le = preprocessing.LabelEncoder()

In [5]:
#Function:Check the data type
def dattype( data ):
    ddtype = 'Error'
    data=data[pd.notnull(data)]
    for i in data:
        ddtype = type(i)
        break
    return ddtype
#convert the data
def typetransform ( data ):
    if dattype( data ) is unicode:
        le.fit( data )
        data = le.transform( data )
    else:
            imp = Imputer(missing_values='NaN', strategy='mean',axis = 1)
            imp.fit(data)
            data = imp.transform( data )
    return data
#delete the data
data = pd.read_excel('C:\\Users\\310249682\\Documents\\data1.xlsx')
del data['HISTORY_HYPERTENSION']
del data['TOTAL_CHOLESTEROL']
del data['CATH EVENTS']
del data['EJECTION_FRACTION']
del data['WEIGHT']
del data['HEIGHT']
del data['HEART_RATE']
del data['Euroscore']
del data['CLINICAL_SYNDROME']
del data['Indication for intervention']
del data['Presenting ECG']
del data['Thrombolysis']
del data['COMPLICATION']
del data['Replacement Device?']
del data['Replacement Reason']
del data['Device type']
del data['Device type.1']
del data['Indication for stent']
del data['LMS Protected']
del data['LENGTH_STAY_PROC_TO_DISCH']
del data['Patient_DB_ID']
del data['Procedure_Unique_Identifier']
#transform the data
for i in data.columns:
    if dattype( data[i] ) is unicode:
        data[i] = typetransform(data[i])
    else:
        data[i] = typetransform(data[i])[0]

C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\numpy\lib\arraysetops.py:200: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))
C:\Ipython\Anaconda2\lib\site-packages\numpy\lib\arraysetops.py:259: FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  return aux[:-1][aux[1:] == aux[:-1]]
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

In [7]:
#balance the data with oversampling and undersampling
out_alive = data[data['OUTCOME'] == 1]
out_dead = data[data['OUTCOME'] == 2]
out_dead_new = pd.concat([out_dead]*5)
out_alive_new = out_alive[0:1265]
data_new = pd.concat([out_alive_new,out_dead_new])

In [13]:
#Random Forest Tree
outcome = 'OUTCOME'
predictors = data.columns
predictors = list(predictors)
del predictors[39]
data_training = data

data_training = data_training[data_training[outcome] != 3]
pre = data_training[predictors] #predictors dataframe
out = typetransform(data_training[outcome]) #outcome dataframe
out_array = np.asarray(out).ravel()
rfc = ske.RandomForestClassifier(n_estimators=1000) #random tree
scores = cross_val_score(rfc, pre, out_array)
pred = cross_val_predict(rfc,pre, out_array)

rfc2 = ske.RandomForestClassifier(n_estimators=1000).fit(pre,out_array)
feature_importance = rfc2.feature_importances_

C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

In [15]:
#Feature Importance
indices = np.argsort(feature_importance)[::-1]
print "Feature Importances:"
for f in range(42):
    print("%d. %s (%f)" % (f + 1, list(data.columns)[f],feature_importance[indices[f]]))

Feature Importances:
1. Procedure Year (0.423118)
2. Procedure Quarter of year (0.083667)
3. Procedure Month (0.041721)
4. Procedure MonthNumber (0.041068)
5. Procedure Week of year (0.040501)
6. Procedure Day of Month (0.038533)
7. Day of Week (0.038416)
8. Time Waiting for Procedure (0.036290)
9. Procedure Group (0.022360)
10. Procedure TypeI (0.021566)
11. Booked Procedure (0.019270)
12. PREVIOUS_MI (0.015021)
13. PREVIOUS_CABG (0.013287)
14. PREVIOUS_PCI (0.011133)
15. RENAL_DISEASE (0.010737)
16. FAMILY_HIST_CAD (0.010492)
17. EJECTION_FRACTION_CAT (0.010352)
18. BMI (0.010306)
19. DIABETES_TYPE (0.010148)
20. DIABETES_CONTROL (0.009854)
21. Smoker (0.008302)
22. ACS (0.008187)
23. ACCESS_TYPE (0.008053)
24. ACCESS_SITE (0.008032)
25. ACCESS_METHOD (0.007349)
26. Radiation Dose (0.005894)
27.  Procedure typeII (0.005612)
28. ARRHYTHMIA? (0.005486)
29. No. of Ablations? (0.005348)
30. No. Vessels Attempted (0.004600)
31. No. Chronic Occlusions Attempted (0.003709)
32. No. Lesions Attempted (0.003273)
33. No. Lesions Successful (0.003214)
34. Largest balloon/Stent Used (0.003104)
35. No. of Restenosis attempted (0.002917)
36. No. Instent restenosis attempted (0.002821)
37. No. Stents Used (0.002200)
38. No. Drug Eluting Stents Used (0.001693)
39. Longest Stent/Treated segment (0.001296)
40. OUTCOME (0.000543)
41. GENDER (0.000389)
42. Age (0.000137)

In [17]:
#CV score
var = [list(data.columns)[i] for i in list(indices[0:25])]
def nrtc_cv( outcome , predictors , data_training ):
    #transform training data
    pre = data_training[predictors] #predictors dataframe
    out = typetransform(data_training[outcome]) #outcome dataframe
    out_array = np.asarray(out).ravel()
    rfc = ske.RandomForestClassifier(n_estimators=1000) #random tree
    scores = cross_val_score(rfc, pre, out_array)
    pred = cross_val_predict(rfc,pre, out_array)
    return scores.mean(),pred
nrtc_cv( 'OUTCOME' , var , data )

C:\Ipython\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

(0.93581186007230566, array([ 1.,  1.,  1., ...,  1.,  1.,  0.]))